version: "3.3"

services:

  samba:
    image: dperson/samba:latest
    restart: unless-stopped
    command: '-u "user1;p4ssw0rd" -s "datos;/datos;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true 
    tmpfs:
      - /tmp 
    environment:
      TZ: 'Europe/Madrid'  
    volumes:
      - ./datos:/datos
        
